### ISSUE TITLE
Implement cmkr vendor

### ISSUE THREAD

**Issue by mrexodia** [MoAlyousef/cmkr#13]
The idea would be to automate https://github.com/MoAlyousef/cmkr/tree/7fdafa41894e5509d03756e3017978ac393e5e13/third_party by declaring it in your `cmake.toml`:

```toml
[project]
name = "vendoring_example"

[vendor]
filesystem = { folder = "third_party/filesystem", url = "https://github.com/gulrak/filesystem/archive/refs/tags/v1.5.4.zip" }
ordered-map = { folder = "third_party/filesystem", url = "https://github.com/Tessil/ordered-map/archive/refs/tags/v1.0.0.tar.gz" }
...
```

Then you can run `cmkr vendor` (likely a wrapper around a cmake script) to download all the files
